### ISSUE TITLE
Would you support WebExtension?

### ISSUE THREAD

**Issue by ivysrono** [disptr/httpheadermangler#8]
For firefox 57+

**Comment by waldens** [comment]
+1
It's a "must have" Add-on. I hope to use it after FF 57. Any plans to port it to webextensions? @disptr

**Comment by NNpranav** [comment]
+1
Would appreciate if this could be ported for 57+ as it's showing as a legacy extension right now.

Thanks!

**Comment by irek** [comment]
+1

**Comment by waldens** [comment]
@ivysrono @NNpranav @irek 
Try [Header Editor](https://addons.mozilla.org/en-US/firefox/addon/header-editor/), not exactly the same, but you might want to try.

**Comment by disptr** [comment]
@ivysrono @waldens @NNpranav @irek Sorry I've been unresponsive. I'll get to work on fixing it for FF 57.

**Comment by disptr** [comment]
@ivysrono @waldens @NNpranav @irek Took me long enough, but I finally sat my ass down, ported it to webextensions, and published it.
